CREATE TABLE T_LANGUAGES
(
    LANGUAGE_ID NUMBER,
    LANGUAGE_NAME VARCHAR2(50) NOT NULL,
    PRIMARY KEY (LANGUAGE_ID)
);

CREATE TABLE T_STATEMENT_TYPES
(
    LANGUAGE_ID NUMBER, 
    STATEMENT_TYPE_ID NUMBER, 
    STATEMENT_TYPE VARCHAR2(100), 
    PARENT_STATEMENT CHAR(1), 
    CLOSE_STATEMENT_TYPE_ID NUMBER, 
    PRIMARY KEY (STATEMENT_TYPE_ID),
    FOREIGN KEY (LANGUAGE_ID) REFERENCES T_LANGUAGES(LANGUAGE_ID)
);

CREATE TABLE T_PROGRAMS
(
    PROGRAM_ID NUMBER,
    LANGUAGE_ID NUMBER,
    PROJECT_NAME VARCHAR2(50),
    PACKAGE_NAME VARCHAR2(100),
    CLASS_NAME VARCHAR2(100),
    PRIMARY KEY (PROGRAM_ID),
    FOREIGN KEY (LANGUAGE_ID) REFERENCES T_LANGUAGES(LANGUAGE_ID)
);

CREATE TABLE T_PROGRAM_STATEMENTS
(
    PROGRAM_STATEMENT_ID NUMBER,
    PROGRAM_ID NUMBER,
    STATEMENT_TYPE_ID NUMBER,
    METHOD_NAME VARCHAR2(100),
    LINE_NUMBER NUMBER, 
    LINE_LENGTH NUMBER,
    PRIMARY KEY (PROGRAM_STATEMENT_ID),
    FOREIGN KEY (PROGRAM_ID) REFERENCES T_PROGRAMS(PROGRAM_ID),
    FOREIGN KEY (STATEMENT_TYPE_ID) REFERENCES T_STATEMENT_TYPES(STATEMENT_TYPE_ID)
);



CREATE TABLE T_PROJECTS(
   ID INT GENERATED ALWAYS AS IDENTITY,
   NAME VARCHAR(255) NOT NULL,
    MAIN_CLASS VARCHAR(255),
    VERSION FLOAT NOT NULL,
    PROG_LANG VARCHAR(255),
    STATUS_CODE INT,
   PRIMARY KEY(ID)
);

CREATE TABLE T_MODULES(
   ID INT GENERATED ALWAYS AS IDENTITY,
   PROJECT_ID INT,
   NAME VARCHAR(255) NOT NULL,
   PACKAGE VARCHAR(255),
  COMMENTS VARCHAR(4000),
    ACTUAL_CODE VARCHAR(4000),
    LINE_NUMBER INT,
   PRIMARY KEY(ID),
   CONSTRAINT fk_mod01
      FOREIGN KEY(PROJECT_ID) 
	  REFERENCES T_PROJECTS(ID)
);

CREATE TABLE T_SUBROUTINES(
   ID INT GENERATED ALWAYS AS IDENTITY,
   MODULE_ID INT,
   DESCRIPTION VARCHAR(4000) ,
   PRIMARY KEY(ID),
   CONSTRAINT fk_mod02
      FOREIGN KEY(MODULE_ID) 
	  REFERENCES T_MODULES(ID)
);

CREATE TABLE T_IMPORTS(
   ID INT GENERATED ALWAYS AS IDENTITY,
   MODULE_ID INT,
    ACTUAL_CODE VARCHAR(4000),
    LINE_NUMBER INT,
   PRIMARY KEY(ID),
   CONSTRAINT fk_mod03
      FOREIGN KEY(MODULE_ID) 
	  REFERENCES T_MODULES(ID)
);

CREATE TABLE T_STATEMENTS(
   ID INT GENERATED ALWAYS AS IDENTITY,
   METHOD_ID INT,
   STATMENT_TYPE VARCHAR(4000) NOT NULL,
    LINE_NUMBER VARCHAR(4000) ,
    COL_NUMBER INT,
    STATMENT VARCHAR(4000) ,
    REF_LINK VARCHAR(255) ,
     COMMENTS VARCHAR(4000) ,
     ACTUAL_CODE VARCHAR(4000) ,
   PRIMARY KEY(ID),
   CONSTRAINT fk_mod03
      FOREIGN KEY(METHOD_ID) 
	  REFERENCES T_SUBROUTINES(ID)
);